Models/BiletGuzergah.cs
using kervanturizm.entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace kervanturizm.webui.Models
{
    public class BiletGuzergah
    {
        public List<kervanturizm.entity.Bilet> Bilets { get; set; }
        public List<Guzergah> Guzergahs { get; set; }
        public List<Sehir> Sehirs { get; set; }

        public Guzergah YeniGuzergah { get; set; }

        public Guzergah GuzergahID { get; set; }
        public string tarih { get; set; }
        public string saat { get; set; }
        public Guzergah gz1 { get; set; }

        public Guzergah gz2 { get; set; }
        public Guzergah gz3 { get; set; }
        public Guzergah Baslangic { get; set; }
        public Guzergah Bitis { get; set; }

        public Bilet bilet { get; set; }

    }
}

Areas/Admin/Controllers/LoginController.cs
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using kervanturizm.entity;
using kervanturizm.data;
using kervanturizm.business;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication;
using kervanturizm.data.Concrete;
using System.Security.Claims;

namespace kervanturizm.webui.Controllers
{
    public class LoginController:Controller
    {
        BiletContext c = new BiletContext();
        public IActionResult Index()
        {

            return View();

        }
public IActionResult GirisYap()
        {
            return View();

        }
        public async Task<IActionResult> AdminList(Admin p)
        {
             var bilgiler = c.Admins.FirstOrDefault(x => x.Kullanici == p.Kullanici && x.Sifre == p.Sifre);
             if (bilgiler != null)
             {
                 var claims = new List<Claim>
                 {
                 new Claim(ClaimTypes.Name,p.Kullanici)
                 };
                 var useridentity = new ClaimsIdentity(claims, "Login");
                 ClaimsPrincipal principal = new ClaimsPrincipal(useridentity);
                 await HttpContext.SignInAsync(principal);
                 return RedirectToAction("Index", "Home");
             }
             return View();

         }
        }





    }

Controllers/AdminController.cs
using kervanturizm.business.Abstract;
using kervanturizm.webui.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace kervanturizm.webui.Controllers
{
    public class AdminController : Controller
    {
        private IBiletService _biletService;
        public AdminController(IBiletService biletService)
        {
            this._biletService = biletService;
        }

        public IActionResult AdminList()
        {
            return View(new BiletGuzergah()
            {
                Bilets = _biletService.GetAll()
            });
        }
        public IActionResult IptalBilet(int BiletID)
        {
            var bilet = _biletService.GetById(BiletID);
            if (bilet!=null)
            {
                _biletService.Delete(bilet);
            }
            return RedirectToAction("AdminList");
        }
    }
}

Controllers/HomeController.cs
using kervanturizm.business.Abstract;
using kervanturizm.webui.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace kervanturizm.webui.Controllers
{
    public class HomeController : Controller
    {

        private ISehirService _sehirService;
        private IGuzergahService _guzergahService;

        public HomeController(ISehirService sehirService, IGuzergahService guzergahService)
        {
            this._sehirService = sehirService;
            this._guzergahService = guzergahService;
        }

      //  [Authorize]
        public IActionResult Index(string nereden, string nereye)
        {

            
            if (nereden == null || nereye == null || nereden == nereye)
            {
                var sehirModel = new BiletGuzergah()
                {
                    Sehirs = _sehirService.GetAll(),
                    Guzergahs = null
                };

                ViewBag.Sehirler = new SelectList(sehirModel.Sehirs, "SehirID", "SehirAd");
                return View(sehirModel);
            }
            else
            {
                var sehirModel = new BiletGuzergah()
                {
                    Sehirs = _sehirService.GetAll(),
                    Guzergahs = _guzergahService.GetYolculuk(nereden, nereye)
                };
                TempData["nereden"] = _guzergahService.GetNereden(nereden);
                TempData["nereye"] = _guzergahService.GetNereye(nereye);
                ViewBag.Sehirler = new SelectList(sehirModel.Sehirs, "SehirID", "SehirAd");
                return View(sehirModel);
            }
            
        }

        public IActionResult Iletisim()
        {
            ViewData["title"] = "İletişim - ";
            return View();
        }

    }
}

Controllers/YolculukController.cs
using kervanturizm.business.Abstract;
using kervanturizm.entity;
using kervanturizm.webui.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace kervanturizm.webui.Controllers
{
    public class YolculukController : Controller
    {
        private IGuzergahService _guzergahService;
        private IBiletService _biletService;

        public YolculukController(IGuzergahService guzergahService, IBiletService biletService)
        {
            
            this._guzergahService = guzergahService;
            this._biletService = biletService;
        }

        public IActionResult Details(int id)
        {
            Guzergah guzergah = _guzergahService.GetGuzergahDetails(id);
            int guzergahKoltukSayisi=_biletService.GetCountByKoltuk(id);
            List<int> dolukoltuklar = _biletService.GetKoltuk(id);
            var koltuklar = new List<int>() { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 };
            foreach (var item in dolukoltuklar)
            {
                koltuklar.Remove(item);
            }
            
            ViewBag.Sayi = guzergahKoltukSayisi;
            ViewBag.Koltuklar = new SelectList(koltuklar); 

            if (guzergah == null)
            {
                return NotFound();
            }
            else
            {
             
                return View(guzergah);
            }
        }

        [HttpPost]
        public IActionResult Details(int GuzergahID, double fiyat, string nereden, string nereye, int koltukno, string email, string isim, string soyisim)
        {
            var entity = new Bilet()
            {
                Ad = isim,
                Soyad=soyisim,
                Mail=email,
                Nereden=nereden,
                Nereye=nereye,
                KoltukNo=koltukno,
                Fiyat=fiyat,
                GuzergahID= GuzergahID
            };
            _biletService.Create(entity);
            return RedirectToAction("Basarili");
        }

        

        public IActionResult Basarili()
        {
            Bilet yeni = _biletService.GetSonKayit();
            int guzergahid = _biletService.GetId();
            string guzergahsaat = _biletService.Getsaat(guzergahid);
            string guzergahtarih = _biletService.Gettarih(guzergahid);

            var BiletGuzergahh = new BiletGuzergah()
            {
                tarih = guzergahtarih,
                saat = guzergahsaat,
                bilet = yeni
            };
            return View(BiletGuzergahh);
        }
    }
}

Views/Admin/AdminList.cshtml
@model BiletGuzergah

<div class="row">
    <div class="col-md-12">
        <h1 class="h3"> Bilet Kontrol</h1> <hr /> <br />
        <table class="table table table-bordered shadow-sm mt-3">
            <thead>
                <tr>
                    <th style="width:20px;">BiletID</th>
                    <th style="width:145px;">Ad - Soyad</th>
                    <th style="">Mail</th>
                    <th style="width:25px;">Başlangıç</th>
                    <th style="width:25px;">Bitiş</th>
                    <th style="width:70px;">KoltukNo</th>
                    <th style="width:80px;">Fiyat</th>
                    <th style="width:85px;">GüzergahNo</th>
                    <th style="width:165px;">İptal</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Bilets.Count > 0)
                {
    @foreach (var item in Model.Bilets)
    {
<tr>
    <td>@item.BiletID</td>
    <td>@item.Ad @item.Soyad</td>
    <td>@item.Mail</td>
    <td>@item.Nereden</td>
    <td>@item.Nereye</td>
    <td>@item.KoltukNo</td>
    <td>@item.Fiyat ₺</td>
    <td>@item.GuzergahID</td>
    <td>
        <form action="/Admin/iptalbilet" method="POST" style="display:inline;">
            <input type="hidden" name="BiletID" value="@item.BiletID" />
            <button type="submit" class="btn btn-danger btn-md mr-2" style="color: white;">Bileti İptal Et</button>
        </form>
    </td>
</tr>} }
                else
                {
    <p>Sistemde henüz kayıtlı bilet yok!</p>}
            </tbody>

        </table>
    </div>
</div>

Views/Home/Iletisim.cshtml
<div class="container row shadow">
    <div class="col-md-6 mt-4 mb-3">
        <h3>Adres</h3><br />
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3011.4874038300695!2d29.021193315276648!3d40.992703979302426!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cab868235b3999%3A0xc59c9d664838f8e5!2zxLBzdGFuYnVsIEtpdGFww6fEsXPEsSBLYWTEsWvDtnk!5e0!3m2!1str!2str!4v1619128516333!5m2!1str!2str" width="350" height="250" style="border:1px;" allowfullscreen="" loading="lazy"></iframe>
        <br />
        <address><br />
            <p><i class="fas fa-map-marker-alt pr-1"></i><i> Kemalpaşa Mahallesi. Üniversite Sokak NO:99/5</i></p>
            <p><i> Serdivan/Sakarya</i></p>
        </address>
    </div>
    
    <div class="col-md-6  mt-4 mb-3">
        <h3>İletişim</h3>
        <br />
        <p><i class="fas fa-phone pr-2"></i> +90 (532) 123 45 67  </p>
        <p><i class="fas fa-at pr-2"></i><a href="mailto:yasarozanakaraman@gmail.com">yasarozanakaraman@gmail.com</a>   </p>
        <p><i class="fab fa-github pr-2"></i> <a href="" style="text-decoration: none;">Yaşar Ozan KARAMAN</a>  </p>
        <p><i class="fab fa-youtube pr-2"></i> <a href="" style="text-decoration: none;">Yaşar Ozan KARAMAN</a>  </p>
    </div>
</div>

Views/Home/Index.cshtml
@model BiletGuzergah

<header class="mt-5">
    @await Html.PartialAsync("_Photo")
</header>


<br />
<br />

<div class="container shadow" style="margin-bottom: 100px; padding: 10px 14px;">
    <div class="form-group" style="display: inline;">
        <form action="/home/index" class="form-inline">
            <select name="nereden" class="form-select form-select-lg mb-3" asp-items="@ViewBag.Sehirler" style="width: 505px; height:53px;">
                <option selected disabled>Kalkış Noktası</option>
            </select>
            <i class="fas fa-long-arrow-alt-right" style="padding: 0px 20px; font-size: 22px;"></i>
            <select name="nereye" class="form-select form-select-lg mb-3" asp-items="@ViewBag.Sehirler" style="width: 505px; height:53px;">
                <option selected disabled>Varış noktası</option>
            </select>
            <button type="submit" class="btn btn-danger btn-lg btn-block">Seferleri Göster</button>
        </form>
    </div>


    @if (Model.Guzergahs != null)
    {
        <div class="row">
            @foreach (var item in @Model.Guzergahs)
            {

                <div class="col-md-6">
                    @await Html.PartialAsync("_yolculugum", item)

                </div>}

        </div> }

    else
    {

        <div class="alert alert danger" role="alert">
            Yolculuk bulunmamaktadır.
        </div>

    }
</div>

Views/Home/_Photo.cshtml
<div id="carouselExampleIndicators" style="width: 99%;  text-align:center; margin: 25px 8px auto;" class="carousel slide shadow" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="~/img/slider1.jpg" alt="Hızlı">
            <div class="carousel-caption d-none d-md-block">
                <h5>Hızlı</h5>
                <p>KervanTurizm araçları sizi gitmek istediğiniz yere hızlıca götürür.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/img/slider2.jpg" alt="Güvenli">
            <div class="carousel-caption d-none d-md-block">
                <h5>Güvenli</h5>
                <p>Gerek araç içi gerek araç dışı güvenlik önlemlerimiz üst seviyededir.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/img/slider3.jpg" alt="Çeşitli">
            <div class="carousel-caption d-none d-md-block">
                <h5 style="color: black;">Çeşitli</h5>
                <p style="color: black;">KervanTurizm ile Türkiye'de adım atmadık yer bırakmayın!</p>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/img/slider4.jpg" alt="Turistik">
            <div class="carousel-caption d-none d-md-block">
                <h5 style="">Turistik</h5>
                <p style="">KervanTurizm ile tüm tarihi ve önemli yapılara hemen bugün bilet alın!</p>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Önceki</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Sonraki</span>
    </a>
</div>

Views/Home/_yolculugum.cshtml
@model Guzergah
<div class="card mb-4 mt-3 shadow">

    <div class="card-body">
        <a class="card-title" asp-controller="Yolculuk" asp-action="Details" asp-route-id="@Model.GuzergahID" style="text-decoration:none; font-size:24px;">@Model.Baslangic <i class="fas fa-long-arrow-alt-right"></i> @Model.Bitis</a>
        <p class="card-text"><b style="font-size:19px;">Güzergah:</b>  @Model.Baslangic > @Model.gz1 > @Model.gz2 > @Model.gz3 > @Model.Bitis</p><br />

        <p style=" font-size:24px; text-align:center;">
            <b>@Model.tarih </b>
            - @Model.tarih
        </p>
    </div>
    <div class="card-footer text-center">
        <a asp-controller="Yolculuk" asp-action="Details" asp-route-id="@Model.GuzergahID" class="btn btn-primary btn-sm">İncele</a>
    </div>
</div>  

Views/Shared/Yolculuk/Basarili.cshtml
@model BiletGuzergah

<div class="container shadow" style="text-align:center;">
    <br />
    <i class="fas fa-check-circle" style="font-size:36px; color:green;"></i><br />
    <br /><p> Sayın @Model.bilet.Ad @Model.bilet.Soyad, @Model.bilet.Nereden -> @Model.bilet.Nereye için bilet alma işleminiz başarılı.</p> <br />
    <a asp-controller="home" asp-action="iletisim">İletişim</a>
    <br /><hr /><br />
    <h3>Bilet Bilgileriniz</h3><br />
    
    <table class="table table table-bordered shadow-sm">
        <thead>
            <tr>
                <th style="width:40px;">Bilet No</th>
                <th style="width:200px;">Ad - Soyad</th>
                <th style="">Mail</th>
                <th style="width:105px;">Başlangıç</th>
                <th style="width:105px;">Bitiş</th>
                <th style="width:60px;">KoltukNo</th>
                <th style="width:80px;">Fiyat</th>
                <th style="width:200px;">tarih - saat</th>
                <th style="width:75px;">Sefer No</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.bilet.BiletID</td>
                <td>@Model.bilet.Ad @Model.bilet.Soyad</td>
                <td>@Model.bilet.Mail</td>
                <td>@Model.bilet.Nereden</td>
                <td>@Model.bilet.Nereye</td>
                <td>@Model.bilet.KoltukNo</td>
                <td>@Model.bilet.Fiyat ₺</td>
                <td>@Model.tarih - @Model.saat</td>
                <td>@Model.bilet.GuzergahID</td>
            </tr>
        </tbody>
    </table>
    <br />
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] KervanTurizm</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <nav>
        <partial name="_navbar" />
    </nav>
    <div class="container">
        @RenderBody()
    </div>

    <footer class="border-top footer text-muted mt-5">
        <div class="container">
            &copy; 2021 - KervanTurizm - Tüm Hakları Saklıdır. | <a asp-area="" asp-controller="Home" asp-action="Iletisim">İletişim</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/214c1c03c5.js" crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_navbar.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">KervanTurizm</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Seyahat">Seyahat Bilgileri</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Kurumsal">Kurumsal</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Iletisim">İletişim</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="AdminList">Yolcu Listesi</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

Views/Yolculuk/Basarili.cshtml
@model BiletGuzergah

<div class="container shadow" style="text-align:center;">
    <br />
    <i class="fas fa-check-circle" style="font-size:36px; color:green;"></i><br />
    <br /><p> Sayın @Model.bilet.Ad @Model.bilet.Soyad, @Model.bilet.Nereden -> @Model.bilet.Nereye için bilet alma işleminiz başarılı.</p> <br />
    <a asp-controller="home" asp-action="iletisim">İletişim</a>
    <br /><hr /><br />
    <h3>Bilet Bilgileriniz</h3><br />

    <table class="table table table-bordered shadow-sm">
        <thead>
            <tr>
                <th style="width:40px;">Bilet No</th>
                <th style="width:200px;">Ad - Soyad</th>
                <th style="">Mail</th>
                <th style="width:105px;">Başlangıç</th>
                <th style="width:105px;">Bitiş</th>
                <th style="width:60px;">KoltukNo</th>
                <th style="width:80px;">Fiyat</th>
                <th style="width:200px;">tarih - saat</th>
                <th style="width:75px;">Sefer No</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.bilet.BiletID</td>
                <td>@Model.bilet.Ad @Model.bilet.Soyad</td>
                <td>@Model.bilet.Mail</td>
                <td>@Model.bilet.Nereden</td>
                <td>@Model.bilet.Nereye</td>
                <td>@Model.bilet.KoltukNo</td>
                <td>@Model.bilet.Fiyat ₺</td>
                <td>@Model.tarih - @Model.saat</td>
                <td>@Model.bilet.GuzergahID</td>
            </tr>
        </tbody>
    </table>
    <br />
</div>